management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: beans, health
    info:
        env:
            enabled: true
server:
    shutdown: graceful
spring:
    application:
        name: ecom-application
    datasource:
        password: ecom-password
        url: jdbc:postgresql://localhost:5432/ecomdb
        username: jamhus
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
