spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: jamhus
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
